### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ghimireprashant** [iDhaval/DTTextField#1]
i have to validate twice to show error.
my code to show error.
    guard !textFieldPassword.text!.isEmptyStr else {
      textFieldPassword.showError = true
      textFieldPassword.errorMessage =  emailMessage
      return false
    }

**Comment by iDhaval** [comment]
Hey @ghimireprashant 

Jus use `textFieldPassword.showError(message: emailMessage)`.

You are using old version of `DTTextField`.

Kindly use latest version of `DTTextField`
