### ISSUE TITLE
RTL language support

### ISSUE THREAD

**Issue by ghimireprashant** [iDhaval/DTTextField#10]
Please add RTL support

**Comment by iDhaval** [comment]
RTL Support added.

**Comment by hamzashahid91** [comment]
![Simulator Screen Shot - iPhone XS - 2019-03-14 at 11 43 04](https://user-images.githubusercontent.com/25819335/54337173-e895c180-464f-11e9-981a-875b4cb3c24e.png)
DTTextfield is not RTL aligned even after adding 
`UIView.appearance().semanticContentAttribute = .forceRightToLeft`
