### ISSUE TITLE
For TextField with DateTimePickerView and PickerView

### ISSUE THREAD

**Issue by jpabanil** [iDhaval/DTTextField#13]
Hi,

It would be great if u can provide this in DateTimePickerView and PickerView

**Comment by iDhaval** [comment]
For that you just have to set inputView of textfield to UIDatePicker or UIPickerView.

let datePicker = UIDatePicker()
txtSample.inputView = datePicker

or

let picker = UIPickerView()
txtSample.inputView = picker

That's it.
