### ISSUE TITLE
textFieldShouldReturn not working

### ISSUE THREAD

**Issue by pavelbowie** [iDhaval/DTTextField#16]
How can I implement textFieldShouldReturn when i press return button on keyboard?

func textFieldShouldReturn(textField: UITextField) -> Bool {
    return true
}

Help me please. This is not calling...

**Comment by iOSDevAkshay** [comment]
Yes delegates are not working

**Comment by iDhaval** [comment]
Have you connected UITextField delegate to respective class?

**Comment by iDhaval** [comment]
Hey @pavelbowie 
Delegates are working as expected. If you are still facing the issue, feel free to reopen the issue.
