### ISSUE TITLE
The text is positioned above the top line using the dtlayer property. Using Xcode 10 and Swift 4.2

### ISSUE THREAD

**Issue by jaag12** [iDhaval/DTTextField#18]
The text is positioned above the top line using the dtlayer property, how can it be solved?

Before Write:
![image1](https://user-images.githubusercontent.com/32569818/46460300-cd2eac80-c7bb-11e8-9707-9093f077bf5d.png)

After Write:
![image2](https://user-images.githubusercontent.com/32569818/46460301-cd2eac80-c7bb-11e8-9068-4d4cd647dd28.png)

Without using the dtlayer property:
![image3](https://user-images.githubusercontent.com/32569818/46470716-ed6c6480-c7d7-11e8-935a-c424b0084f4e.png)

**Comment by iDhaval** [comment]
Bottom border support added
