### ISSUE TITLE
Not able to change errorlabel alignment change

### ISSUE THREAD

**Issue by kanakaraju043** [iDhaval/DTTextField#20]
Not able to change errorlabel alignment change

**Comment by iDhaval** [comment]
@kanakaraju043 I know it is too late to respond but if you still remember this issue. Can you be more specific?

**Comment by vijayprmar** [comment]
<img width="299" alt="Screenshot 2020-04-27 at 5 43 21 PM" src="https://user-images.githubusercontent.com/53894954/80370894-9ee95400-88ae-11ea-9df6-a404eef73581.png">
 Facing this issue

**Comment by iDhaval** [comment]
@vspxcoder Hope you didn't give height constraint to textfield, if not please provide more details

**Comment by SatyamViba** [comment]
> @vspxcoder Hope you didn't give height constraint to textfield, if not please provide more details

Its working if we remove the height constraint. Thanks.
