### ISSUE TITLE
Issue with Textfield background colour 

### ISSUE THREAD

**Issue by Ravinder-webonise** [iDhaval/DTTextField#26]
How to change the background colour of Ui textfield  , If i changed the background colour from Xcode then there is issue with the background colour of the textfield . After changing the colour it still showing white background colour. Tried Tint colour also but nothing works.

**Comment by iDhaval** [comment]
You can change it through `dtLayer` property

**Comment by Ravinder-webonise** [comment]
yes i had resolved this issue.
Thanks
