### ISSUE TITLE
Xcode 9 swift 4 crash iOS 11

### ISSUE THREAD

**Issue by jsalazar78** [iDhaval/DTTextField#5]
DTTextField_Example[5003:262200] [Accessibility] ****************** Loading GAX Client Bundle ****************
fatal error: unexpectedly found nil while unwrapping an Optional value
2017-09-21 17:44:22.977669-0500 DTTextField_Example[5003:262200] fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by jsalazar78** [comment]
Sorry I missed last comments I Try the code below and it work.

fileprivate func insetRectForBounds(rect:CGRect) -> CGRect {
   // guard !lblFloatPlaceholder.text!.isEmptyStr else { return insetRectForEmptyBounds(rect: rect) }

Just comment the above line, got it work.

**Comment by iDhaval** [comment]
Hey,
I have resolved that crash. you can update your pod.
Kindly close this issue
Thank you
